# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'DouYuUI' do
  #网络请求
  pod 'Alamofire','5.4.4'
  
  #图片下载
  pod 'Kingfisher','5.15.8'
  
  #Json 和 Model转换
  pod 'HandyJSON'
  
  #上拉/下拉
  pod 'ESPullToRefresh'
  
  #轮播图
  pod 'FSPagerView'
  
  #键盘处理
  pod 'IQKeyboardManagerSwift'
  
  #自动布局
  pod 'SnapKit'
  
  #网络状态检测
  pod 'Reachability'
  
  #本地存储
  pod 'SwiftyUserDefaults'
  
  #定时器
  pod 'SwiftyTimer'
  
  #系统钥匙串
  pod 'KeychainAccess'
  
  #指示器
  pod 'NVActivityIndicatorView'
  
  #GPUImage2 图片、视频等GPU加速处理
  pod 'GPUImage2'
  
  # Swift 5 轻量级聊天框架
  pod 'Chatto', '= 4.1.0'
  pod 'ChattoAdditions', '= 4.1.0' # if you want to use the cells or the input component
  
end
