# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'DouYuUI' do
  pod 'Alamofire','5.4.4'
  pod 'HandyJSON'
  pod 'Kingfisher','5.15.8'
end
